# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebb6f3893987dd07cc43fba7bb88928f704d5f31012845046a725bb8360754ce657cfb69440d834c7d92f794a1878cb3f675587e81ec684ff8a3677811668634

test:
  secret_key_base: 981a299612ce36cbc0212757537abf88f0920ba0e394f91c07fcf86d352cb806bddaa752df7bb907d043655363e9140c29d767f3389f5197dab4cc699d2d3577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
